---
version: '3.8'

networks:
  webapp:

services:
  #Ngix
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
    - "8000:80"
    links:
      - tradler-php
    volumes:
      - ./:/var/www/html
      - ./Docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./Docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - tradler-php
      - tradler-db
    networks:
      - webapp
  #The App build
  tradler-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - "9001:9000"
    depends_on:
      - tradler-db
      - tradler-redis
    networks:
      - webapp

  tradler-queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_queue
    volumes:
      - ./:/var/www/html
    depends_on:
      - tradler-php
    networks:
      - webapp
    command: ["php", "artisan", "queue:work"]

  ## MySQL Docker Compose Config
  tradler-db:
    container_name: ${APP_NAME}_mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    networks:
      - webapp

  ## Redis Server
  tradler-redis:
    container_name: ${APP_NAME}_redis
    image: redis:6.2-alpine
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    networks:
      - webapp


volumes:
  db-data: ~